[project]
name = "lab01-basic-agent"
version = "0.1.0"
description = "A minimal AI agent interacting with a local LLM through Ollama"
readme = "README.md"
authors = [
    { name = "Angel Elbaz", email = "22364064+aelbazsanz@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ollama>=0.6.2",
    "python-dotenv>=1.2.3",
]

[project.scripts]
lab01-basic-agent = "lab01_basic_agent:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
