services:
  agent:
    image: ai-agents-lab03-agent:latest
    container_name: ai-agents-lab03-agent
    stdin_open: true
    tty: true
    networks:
      - llm-network
      - target-network
    environment:
      OLLAMA_HOST: http://ollama:11434
      OLLAMA_MODEL: qwen3:8b
      TARGET_HOST: target
      AGENT_USER: analyst

  target:
    image: ai-agents-lab03-target:latest
    container_name: ai-agents-lab03-target
    networks:
      - target-network

networks:
  llm-network:
    external: true
    name: ai-agents-llm

  target-network:
    internal: true